KailoTown_DeliciousCafe_Text_LenaHiTina::
    .string "Hi, {PLAYER}!\n"
    .string "Are you looking for TINA?$"

KailoTown_DeliciousCafe_Text_LenaHiDan::
    .string "Hi, {PLAYER}!\n"
    .string "Are you looking for DAN?$"

KailoTown_DeliciousCafe_Text_LenaTinaSleeps::
    .string "I'm really sorry, but she's\n"
    .string "still sleeping...\p"
    .string "Maybe you should come back\n"
    .string "later, okay?$"

KailoTown_DeliciousCafe_Text_LenaDanSleeps::
    .string "I'm really sorry, but he's\n"
    .string "still sleeping...\p"
    .string "Maybe you should come back\n"
    .string "later, okay?$"

KailoTown_DeliciousCafe_Text_LenaTinaAwake::
    .string "She just woke up.\n"
    .string "I'll call her here, okay?$"

KailoTown_DeliciousCafe_Text_LenaDanAwake::
    .string "He just woke up.\n"
    .string "I'll call him here, okay?$"

KailoTown_DeliciousCafe_Text_LenaTinaCome::
    .string "TINA! Come here!\n"
    .string "{PLAYER} is looking for you!$"

KailoTown_DeliciousCafe_Text_LenaDanCome::
    .string "DAN! Come here!\n"
    .string "{PLAYER} is looking for you!$"

KailoTown_DeliciousCafe_Text_TinaHelloPlayer::
    .string "TINA: Hi, {PLAYER}!"

KailoTown_DeliciousCafe_Text_DanHelloPlayer::
    .string "DAN: Hi, {PLAYER}!"

KailoTown_DeliciousCafe_Text_LenaTinaJump::
    .string "LENA: TINA!\p"
    .string "How many times do I have\n"
    .string "to tell you?\l"
    .string "No more jumping over counter!$"

KailoTown_DeliciousCafe_Text_LenaDanJump::
    .string "LENA: DAN!\p"
    .string "How many times do I have\n"
    .string "to tell you?\l"
    .string "No more jumping over counter!$"

KailoTown_DeliciousCafe_Text_TinaSorry::
    .string "TINA: Sorry, mom...$"

KailoTown_DeliciousCafe_Text_DanSorry::
    .string "DAN: Sorry, mom...$"

KailoTown_DeliciousCafe_Text_RivalGuess::
    .string "Guess what, {PLAYER}!\p"
    .string "Mom gave me a POKéMON$"

KailoTown_DeliciousCafe_Text_RivalAdventure::
    .string "You know what that means?\p"
    .string "I'm going for an adventure\n"
    .string "with you and {RIVAL}!\l"
    .string "Isn't that exciting?\p"
    .string "I'm gonna show him my SNUBULL\n"
    .string "right now!\l"
    .string "Bye!$"

KailoTown_DeliciousCafe_Text_LenaSigh::
    .string "LENA: Ha, ha...\n"
    .string "...children...\p"
    .string "Before you know it, they're\n"
    .string "already flying out of the nest...\l"
    .string "Take care you three out there, okay?$"