KailoTown_ProfBlackbirdsLab_Text_Laigen::
    .string "“PROF. LAIGEN”\p"
    .string "“The founder of POKéMON RESEARCH\n"
    .string "LAB in MOON VALLEY”$"

KailoTown_ProfBlackbirdsLab_Text_Mail::
    .string "There's an e-mail message here.\p"
    .string  "...\n"
    .string "...\p"
    .string "“Hi, VICTOR!\n"
    .string "First, I must say that parents\l"
    .string "were telling the truth\p"
    .string "UNOVA is so beautifull...\p"
    .string "...but I can't wait to return\n"
    .string "to KANTO...\p"
    .string "And... You were right.\p"
    .string "The rumors were true.\n"
    .string "I saw fallen trees and broken roofs\p"
    .string "If it's really her, and it's SHE,\n"
    .string "then our Old Man will have a partner!\p"
    .string "You should come here soon\n"
    .string "and bring him here.\p"
    .string "And PROF. LAIGEN too!\p"
    .string "I must go, get back to\n"
    .string "the work...\p"
    .string "Your sister,\n"
    .string "HELEN”$"

KailoTown_ProfBlackbirdsLab_Text_PC::
    .string "There's tons of TOWN MAPs and\n"
    .string "latest world news opened here...\p"
    .string "...and a notepad hidden\n"
    .string "under windows.\p"
    .string "Check it out?$"

KailoTown_ProfBlackbirdsLab_Text_PCYes::
    .string "There's “ROCKET” word here\n"
    .string "and bunch of names...\p"
    .string "There's also a question\n"
    .string "at the end of file.\p"
    .string "“EVANLYN,\n"
    .string "where are you?”$"

KailoTown_ProfBlackbirdsLab_Text_PCNo::
    .string "Nah...\n"
    .string "Better don't mess with it...$"
