KailoTown_PlayersHouse_1F_Text_MomTalk::
    .string "Take care of yourself!\n"
    .string "And don't fight with {RIVAL}, okay?$"

KailoTown_PlayersHouse_1F_Text_MomPlayer::
    .string "MOM: {PLAYER}!$"

KailoTown_PlayersHouse_1F_Text_MomAwake::
    .string "You're awake!\p"
    .string "{RIVAL} went out earlier\n"
    .string "you slept like a rock.\p"
    .string "Sigh...\p"
    .string "I'm not suprised at all,\n"
    .string "after such a downpour...\p"
    .string "Do you have everything?$"

KailoTown_PlayersHouse_1F_Text_MomGameboyDan::
    .string "You didn't took your GAMEBOY,\n"
    .string "did you?\p"
    .string "I wouldn't understand it at all if\n"
    .string "you played those POKéMON games right\l"
    .string "before you'll get the real one...\p"
    .string "I knew that GOLD was a wonderful\n"
    .string "TRAINER, but remember\l"
    .string "to remain yourself.\p"
    .string "Sigh...\p"
    .string "Now go,\n"
    .string "And take care of yourself\l"
    .string "I'll keep your room clean.$"

KailoTown_PlayersHouse_1F_Text_MomGameboyTina::
    .string "You didn't took your GAMEBOY,\n"
    .string "did you?\p"
    .string "I wouldn't understand it at all if\n"
    .string "you played those POKéMON games right\l"
    .string "before you'll get the real one...\p"
    .string "I knew that CRYSTAL was a wonderful\n"
    .string "TRAINER, but remember\l"
    .string "to remain yourself.\p"
    .string "Sigh...\p"
    .string "Now go,\n"
    .string "And take care of yourself\l"
    .string "I'll keep your room clean.$"
